"""initial schema

Revision ID: 8560a5ee1c83
Revises: 
Create Date: 2026-05-08 17:55:39.574012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8560a5ee1c83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_hash', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('machine_name', sa.String(length=128), nullable=True),
    sa.Column('machine_model', sa.String(length=64), nullable=True),
    sa.Column('chip_type', sa.String(length=64), nullable=True),
    sa.Column('physical_memory', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_chip_type'), 'machines', ['chip_type'], unique=False)
    op.create_index(op.f('ix_machines_machine_model'), 'machines', ['machine_model'], unique=False)
    op.create_index(op.f('ix_machines_serial_hash'), 'machines', ['serial_hash'], unique=True)
    op.create_index(op.f('ix_machines_slug'), 'machines', ['slug'], unique=True)
    op.create_table('drives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('media_name', sa.String(length=128), nullable=False),
    sa.Column('bus_protocol', sa.String(length=32), nullable=True),
    sa.Column('internal', sa.Boolean(), nullable=False),
    sa.Column('solid_state', sa.Boolean(), nullable=False),
    sa.Column('size_gb', sa.Float(), nullable=True),
    sa.Column('enclosure_name', sa.String(length=128), nullable=True),
    sa.Column('enclosure_vendor', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'media_name', name='uq_drives_machine_media')
    )
    op.create_index(op.f('ix_drives_bus_protocol'), 'drives', ['bus_protocol'], unique=False)
    op.create_index('ix_drives_enclosure_name', 'drives', ['enclosure_name'], unique=False)
    op.create_index(op.f('ix_drives_internal'), 'drives', ['internal'], unique=False)
    op.create_index(op.f('ix_drives_machine_id'), 'drives', ['machine_id'], unique=False)
    op.create_index('ix_drives_media_name', 'drives', ['media_name'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('drive_a_id', sa.Integer(), nullable=False),
    sa.Column('drive_b_id', sa.Integer(), nullable=True),
    sa.Column('label_a', sa.String(length=128), nullable=False),
    sa.Column('label_b', sa.String(length=128), nullable=True),
    sa.Column('quick', sa.Boolean(), nullable=False),
    sa.Column('size_multiplier', sa.Float(), nullable=False),
    sa.Column('script_version', sa.String(length=32), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['drive_a_id'], ['drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drive_b_id'], ['drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_machine_id'), 'runs', ['machine_id'], unique=False)
    op.create_index(op.f('ix_runs_slug'), 'runs', ['slug'], unique=True)
    op.create_index(op.f('ix_runs_ts'), 'runs', ['ts'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('drive_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('primary_unit', sa.String(length=16), nullable=False),
    sa.Column('primary_value', sa.Float(), nullable=False),
    sa.Column('read_bw_mb', sa.Float(), nullable=True),
    sa.Column('read_iops', sa.Float(), nullable=True),
    sa.Column('read_lat_us_mean', sa.Float(), nullable=True),
    sa.Column('read_lat_us_p50', sa.Float(), nullable=True),
    sa.Column('read_lat_us_p99', sa.Float(), nullable=True),
    sa.Column('read_lat_us_p999', sa.Float(), nullable=True),
    sa.Column('write_bw_mb', sa.Float(), nullable=True),
    sa.Column('write_iops', sa.Float(), nullable=True),
    sa.Column('write_lat_us_mean', sa.Float(), nullable=True),
    sa.Column('write_lat_us_p50', sa.Float(), nullable=True),
    sa.Column('write_lat_us_p99', sa.Float(), nullable=True),
    sa.Column('write_lat_us_p999', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_category'), 'test_results', ['category'], unique=False)
    op.create_index(op.f('ix_test_results_drive_id'), 'test_results', ['drive_id'], unique=False)
    op.create_index('ix_test_results_drive_test', 'test_results', ['drive_id', 'test_name'], unique=False)
    op.create_index(op.f('ix_test_results_run_id'), 'test_results', ['run_id'], unique=False)
    op.create_index('ix_test_results_test_value', 'test_results', ['test_name', 'primary_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_results_test_value', table_name='test_results')
    op.drop_index(op.f('ix_test_results_run_id'), table_name='test_results')
    op.drop_index('ix_test_results_drive_test', table_name='test_results')
    op.drop_index(op.f('ix_test_results_drive_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_category'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_runs_ts'), table_name='runs')
    op.drop_index(op.f('ix_runs_slug'), table_name='runs')
    op.drop_index(op.f('ix_runs_machine_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index('ix_drives_media_name', table_name='drives')
    op.drop_index(op.f('ix_drives_machine_id'), table_name='drives')
    op.drop_index(op.f('ix_drives_internal'), table_name='drives')
    op.drop_index('ix_drives_enclosure_name', table_name='drives')
    op.drop_index(op.f('ix_drives_bus_protocol'), table_name='drives')
    op.drop_table('drives')
    op.drop_index(op.f('ix_machines_slug'), table_name='machines')
    op.drop_index(op.f('ix_machines_serial_hash'), table_name='machines')
    op.drop_index(op.f('ix_machines_machine_model'), table_name='machines')
    op.drop_index(op.f('ix_machines_chip_type'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
